<template>
    <Link
        class="
            bg-lightBlue-500
            text-white
            active:bg-lightBlue-600
            font-bold
            uppercase
            text-xs
            px-4
            py-2
            rounded
            shadow
            hover:shadow-md
            outline-none
            focus:outline-none
            mr-1
            mb-1
            ease-linear
            transition-all
            duration-150
        "
        >Edit</Link
    >
    &nbsp;&nbsp;&nbsp;
    <Link
        class="
            bg-red-500
            text-white
            active:bg-red-600
            font-bold
            uppercase
            text-xs
            px-4
            py-2
            rounded
            shadow
            hover:shadow-md
            outline-none
            focus:outline-none
            mr-1
            mb-1
            ease-linear
            transition-all
            duration-150
        "
        >Hapus</Link
    >
</template>
<script>
import { Link } from "@inertiajs/inertia-vue3";
export default {
    props: ["id"],
    components: {
        Link,
    },
};
</script>
